/**
 * Validation gate for src/lib/skills/merkle.ts (the user's "no work without a validation check" rule).
 * Nothing in the transparency-log phases ships until this is green: `npm run skills:test`.
 *
 * The merkle lib is anchored to RFC 6962 / RFC 9162 three ways, each independent of the lib's own code path:
 *   1. Domain-separation anchors — n=0,1,2,3 roots computed inline with raw createHash + the literal
 *      0x00/0x01 prefixes, pinning the leaf/node formulas to the standard text (not to merkle.ts).
 *   2. Independent naive oracle — a dead-simple recursive MTH (`refRoot`) sharing no code with merkle.ts;
 *      roots must match across all sizes 0..40.
 *   3. Proof round-trips against the oracle — every inclusion/consistency proof generated by the lib must
 *      verify (via the lib's RFC 9162 iterative verifier) against the INDEPENDENT oracle root, and every
 *      single-byte tamper (leaf, root, index, proof element, sizes) must be rejected.
 */
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import {
  EMPTY_TREE_ROOT,
  leafHash,
  nodeHash,
  merkleRoot,
  inclusionProof,
  consistencyProof,
  verifyInclusion,
  verifyConsistency,
} from '../../../src/lib/skills/merkle.ts';

const sha256hex = (buf: Buffer) => createHash('sha256').update(buf).digest('hex');
const rawLeaf = (s: string) => sha256hex(Buffer.concat([Buffer.from([0x00]), Buffer.from(s, 'utf8')]));
const rawNode = (l: string, r: string) =>
  sha256hex(Buffer.concat([Buffer.from([0x01]), Buffer.from(l, 'hex'), Buffer.from(r, 'hex')]));

/** Independent naive Merkle Tree Hash (RFC 6962 §2.1) — the oracle. Shares NO code with merkle.ts. */
function refRoot(leaves: string[]): string {
  const n = leaves.length;
  if (n === 0) return sha256hex(Buffer.alloc(0));
  if (n === 1) return leaves[0];
  let k = 1;
  while (k * 2 < n) k *= 2;
  return rawNode(refRoot(leaves.slice(0, k)), refRoot(leaves.slice(k)));
}

const entries = (n: number) => Array.from({ length: n }, (_, i) => `record-${i}`);
const leavesFor = (n: number) => entries(n).map(leafHash);

test('domain-separation anchors (raw SHA-256 with 0x00/0x01 prefixes)', () => {
  assert.equal(EMPTY_TREE_ROOT, sha256hex(Buffer.alloc(0)), 'empty tree = SHA-256("")');
  assert.equal(merkleRoot([]), sha256hex(Buffer.alloc(0)));
  // n=1: root is the leaf hash itself
  assert.equal(leafHash(''), rawLeaf(''));
  assert.equal(merkleRoot([leafHash('a')]), rawLeaf('a'));
  // n=2: root = node(leaf a, leaf b)
  assert.equal(nodeHash(leafHash('a'), leafHash('b')), rawNode(rawLeaf('a'), rawLeaf('b')));
  assert.equal(merkleRoot([leafHash('a'), leafHash('b')]), rawNode(rawLeaf('a'), rawLeaf('b')));
  // n=3: split k=2 → node( node(a,b), c )
  const expect3 = rawNode(rawNode(rawLeaf('a'), rawLeaf('b')), rawLeaf('c'));
  assert.equal(merkleRoot(['a', 'b', 'c'].map(leafHash)), expect3);
});

test('merkleRoot matches the independent oracle for all sizes 0..40', () => {
  for (let n = 0; n <= 40; n++) {
    assert.equal(merkleRoot(leavesFor(n)), refRoot(leavesFor(n)), `root mismatch at n=${n}`);
  }
});

test('inclusion proofs verify against the oracle root for every index, sizes 1..40', () => {
  for (let n = 1; n <= 40; n++) {
    const leaves = leavesFor(n);
    const root = refRoot(leaves); // independent oracle
    for (let i = 0; i < n; i++) {
      const proof = inclusionProof(leaves, i);
      assert.ok(verifyInclusion(leaves[i], i, n, proof, root), `inclusion failed n=${n} i=${i}`);
    }
  }
});

test('inclusion proofs reject tampering', () => {
  const n = 23;
  const leaves = leavesFor(n);
  const root = refRoot(leaves);
  const i = 7;
  const proof = inclusionProof(leaves, i);
  assert.ok(verifyInclusion(leaves[i], i, n, proof, root));
  // wrong leaf
  assert.ok(!verifyInclusion(leafHash('not-the-leaf'), i, n, proof, root));
  // wrong index
  assert.ok(!verifyInclusion(leaves[i], i + 1, n, proof, root));
  // wrong root
  assert.ok(!verifyInclusion(leaves[i], i, n, proof, leafHash('wrong-root')));
  // tampered proof element
  if (proof.length) {
    const bad = [...proof];
    bad[0] = leafHash('tampered');
    assert.ok(!verifyInclusion(leaves[i], i, n, bad, root));
  }
  // out-of-range index
  assert.ok(!verifyInclusion(leaves[0], n, n, inclusionProof(leaves, 0), root));
});

test('consistency proofs verify against the oracle roots for all 1<=m<=n<=40', () => {
  for (let n = 1; n <= 40; n++) {
    const leaves = leavesFor(n);
    const secondRoot = refRoot(leaves);
    for (let m = 1; m <= n; m++) {
      const firstRoot = refRoot(leaves.slice(0, m));
      const proof = consistencyProof(leaves, m, n);
      assert.ok(
        verifyConsistency(m, n, firstRoot, secondRoot, proof),
        `consistency failed m=${m} n=${n}`,
      );
    }
  }
});

test('consistency proofs reject rollback / tampering', () => {
  const n = 17;
  const m = 11;
  const leaves = leavesFor(n);
  const firstRoot = refRoot(leaves.slice(0, m));
  const secondRoot = refRoot(leaves);
  const proof = consistencyProof(leaves, m, n);
  assert.ok(verifyConsistency(m, n, firstRoot, secondRoot, proof));
  // forged second root (equivocation / split view)
  assert.ok(!verifyConsistency(m, n, firstRoot, leafHash('forged-head'), proof));
  // forged first root (claiming a different past)
  assert.ok(!verifyConsistency(m, n, leafHash('forged-past'), secondRoot, proof));
  // tampered proof
  if (proof.length) {
    const bad = [...proof];
    bad[bad.length - 1] = leafHash('tampered');
    assert.ok(!verifyConsistency(m, n, firstRoot, secondRoot, bad));
  }
  // rollback: present an OLD tree (size m) as if it were the newer head of size n
  const oldAsHead = refRoot(leaves.slice(0, m));
  assert.ok(!verifyConsistency(m, n, firstRoot, oldAsHead, proof));
});

test('m == n consistency is the empty proof', () => {
  const leaves = leavesFor(9);
  const root = refRoot(leaves);
  assert.deepEqual(consistencyProof(leaves, 9, 9), []);
  assert.ok(verifyConsistency(9, 9, root, root, []));
  assert.ok(!verifyConsistency(9, 9, root, leafHash('x'), []));
});
